version: '2'
services:
  parse_dont_validate_postgres:
    image: postgres:12
    command: ["postgres", "-c", "log_min_duration_statement=1000", "-c", "log_destination=stderr"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: password